platform :ios, '8.0'

target 'AKGPushAnimatorTableviewDemo' do
  use_frameworks!

pod 'AKGPushAnimator', '~> 1.0.3'

  target 'AKGPushAnimatorTableviewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AKGPushAnimatorTableviewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
